apiVersion: services.tanzu.vmware.com/v1
kind: ServiceBinding
metadata:
    name: music-33a914
spec:
  alias: music
  serviceRef:
    apiGroup: bitnami.database.tanzu.vmware.com
    kind: MySQLInstance
    name: music
  targetRef:
    apiGroup: apps.tanzu.vmware.com
    kind: ContainerApp
    name: mysql-music
